require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/plant_species", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PlantSpecy. As you add validations to PlantSpecy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: Faker::Food.vegetables}
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlantSpecy.create! valid_attributes
      get plant_species_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      plant_specy = PlantSpecy.create! valid_attributes
      get plant_specy_url(plant_specy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_plant_specy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      plant_specy = PlantSpecy.create! valid_attributes
      get edit_plant_specy_url(plant_specy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlantSpecy" do
        expect {
          post plant_species_url, params: { plant_specy: valid_attributes }
        }.to change(PlantSpecy, :count).by(1)
      end

      it "redirects to the created plant_specy" do
        post plant_species_url, params: { plant_specy: valid_attributes }
        expect(response).to redirect_to(plant_specy_url(PlantSpecy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlantSpecy" do
        expect {
          post plant_species_url, params: { plant_specy: invalid_attributes }
        }.to change(PlantSpecy, :count).by(0)
      end

      it "renders a fail response (i.e. to display the 'new' template)" do
        post plant_species_url, params: { plant_specy: invalid_attributes }
        expect(response).to_not be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {name: Faker::Food.vegetables}
      }

      it "updates the requested plant_specy" do
        plant_specy = PlantSpecy.create! valid_attributes
        patch plant_specy_url(plant_specy), params: { plant_specy: new_attributes }
        plant_specy.reload
        expect(plant_specy.name).to eq(new_attributes[:name])
      end

      it "redirects to the plant_specy" do
        plant_specy = PlantSpecy.create! valid_attributes
        patch plant_specy_url(plant_specy), params: { plant_specy: new_attributes }
        plant_specy.reload
        expect(response).to redirect_to(plant_specy_url(plant_specy))
      end
    end

    context "with invalid parameters" do
      it "renders a fail response (i.e. to display the 'edit' template)" do
        plant_specy = PlantSpecy.create! valid_attributes
        patch plant_specy_url(plant_specy), params: { plant_specy: invalid_attributes }
        expect(response).to_not be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested plant_specy" do
      plant_specy = PlantSpecy.create! valid_attributes
      expect {
        delete plant_specy_url(plant_specy)
      }.to change(PlantSpecy, :count).by(-1)
    end

    it "redirects to the plant_species list" do
      plant_specy = PlantSpecy.create! valid_attributes
      delete plant_specy_url(plant_specy)
      expect(response).to redirect_to(plant_species_url)
    end
  end
end
