require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/productive_properties", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProductiveProperty. As you add validations to ProductiveProperty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProductiveProperty.create! valid_attributes
      get productive_properties_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      productive_property = ProductiveProperty.create! valid_attributes
      get productive_property_url(productive_property)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_productive_property_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      productive_property = ProductiveProperty.create! valid_attributes
      get edit_productive_property_url(productive_property)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProductiveProperty" do
        expect {
          post productive_properties_url, params: { productive_property: valid_attributes }
        }.to change(ProductiveProperty, :count).by(1)
      end

      it "redirects to the created productive_property" do
        post productive_properties_url, params: { productive_property: valid_attributes }
        expect(response).to redirect_to(productive_property_url(ProductiveProperty.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProductiveProperty" do
        expect {
          post productive_properties_url, params: { productive_property: invalid_attributes }
        }.to change(ProductiveProperty, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post productive_properties_url, params: { productive_property: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested productive_property" do
        productive_property = ProductiveProperty.create! valid_attributes
        patch productive_property_url(productive_property), params: { productive_property: new_attributes }
        productive_property.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the productive_property" do
        productive_property = ProductiveProperty.create! valid_attributes
        patch productive_property_url(productive_property), params: { productive_property: new_attributes }
        productive_property.reload
        expect(response).to redirect_to(productive_property_url(productive_property))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        productive_property = ProductiveProperty.create! valid_attributes
        patch productive_property_url(productive_property), params: { productive_property: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested productive_property" do
      productive_property = ProductiveProperty.create! valid_attributes
      expect {
        delete productive_property_url(productive_property)
      }.to change(ProductiveProperty, :count).by(-1)
    end

    it "redirects to the productive_properties list" do
      productive_property = ProductiveProperty.create! valid_attributes
      delete productive_property_url(productive_property)
      expect(response).to redirect_to(productive_properties_url)
    end
  end
end
